-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 23:26:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `numRue` VARCHAR(45) NOT NULL,
  `nomRue` VARCHAR(45) NOT NULL,
  `nomVille` VARCHAR(45) NOT NULL,
  `nomProvince` VARCHAR(45) NOT NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `firstLogin` VARCHAR(45) BINARY NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `usename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`, `password`, `usename`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `idPatient` INT NOT NULL AUTO_INCREMENT,
  `nomPatient` VARCHAR(45) NOT NULL,
  `prenomPatient` VARCHAR(45) NOT NULL,
  `ramqPatient` VARCHAR(12) NOT NULL,
  `numSequence` CHAR(2) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `sexePatient` CHAR(1) NOT NULL,
  `courrielPatient` VARCHAR(45) NOT NULL,
  `idAdresse` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPatient`, `idAdresse`, `idUtilisateur`),
  UNIQUE INDEX `ramqPatient_UNIQUE` (`ramqPatient` ASC) VISIBLE,
  INDEX `fk_patient_localisation_idx` (`idAdresse` ASC) VISIBLE,
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_patient_localisation`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdresse`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Services` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `idServices` INT NOT NULL,
  `typeServices` VARCHAR(45) NOT NULL,
  `idClinique` INT NOT NULL,
  PRIMARY KEY (`idServices`, `idClinique`),
  INDEX `idClinique_idx` (`idClinique` ASC) VISIBLE,
  CONSTRAINT `idClinique`
    FOREIGN KEY (`idClinique`)
    REFERENCES `mydb`.`clinique` (`idClinique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clinique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clinique` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clinique` (
  `idClinique` INT NOT NULL AUTO_INCREMENT,
  `nomClinique` VARCHAR(45) NULL,
  `courrielClinique` VARCHAR(45) NOT NULL,
  `telClinique` VARCHAR(45) NOT NULL,
  `idAdresse` INT NOT NULL,
  `idMedecin` INT NOT NULL,
  `idServices` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idClinique`, `idAdresse`, `idMedecin`, `idServices`, `idUtilisateur`),
  INDEX `idAdresse_idx` (`idAdresse` ASC) VISIBLE,
  INDEX `idService_idx` (`idServices` ASC) VISIBLE,
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  INDEX `idMedecin_idx` (`idMedecin` ASC) VISIBLE,
  CONSTRAINT `idMedecin`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `mydb`.`medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdresse`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServices`
    FOREIGN KEY (`idServices`)
    REFERENCES `mydb`.`Services` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disponibiliteMed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disponibiliteMed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disponibiliteMed` (
  `idPlageHoraire` INT NOT NULL,
  `jourSemaine` VARCHAR(8) NULL,
  `heureDebut` TIME NULL,
  `heureFin` TIME NULL,
  `statutDispo` TINYINT NULL,
  `idMedecin` INT NOT NULL,
  PRIMARY KEY (`idPlageHoraire`, `idMedecin`),
  INDEX `idMedecin_idx` (`idMedecin` ASC) VISIBLE,
  CONSTRAINT `idMedecin`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `mydb`.`medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services Medecin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Services Medecin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Services Medecin` (
  `idServices Medecin` INT NOT NULL,
  `idMedecin` INT NOT NULL,
  `idServices` INT NOT NULL,
  PRIMARY KEY (`idServices Medecin`, `idMedecin`, `idServices`),
  INDEX `idservicesMedecin_idx` (`idMedecin` ASC) VISIBLE,
  INDEX `idServices_idx` (`idServices` ASC) VISIBLE,
  CONSTRAINT `idservicesMedecin`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `mydb`.`disponibiliteMed` (`idPlageHoraire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMedecin`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `mydb`.`medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServices`
    FOREIGN KEY (`idServices`)
    REFERENCES `mydb`.`Services` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medecin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medecin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medecin` (
  `idMedecin` INT NOT NULL AUTO_INCREMENT,
  `nomMedecin` VARCHAR(45) NOT NULL,
  `prenomMedecin` VARCHAR(45) NOT NULL,
  `specMedecin` VARCHAR(45) NOT NULL,
  `courrielMed` VARCHAR(45) NOT NULL,
  `numProfession` VARCHAR(45) NOT NULL,
  `typeFacturation` VARCHAR(45) NOT NULL,
  `idClinique` INT NOT NULL,
  `idPlageHoraire` INT NOT NULL,
  `idServices` INT NOT NULL,
  `idAdresse` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idMedecin`, `idClinique`, `idPlageHoraire`, `idServices`, `idAdresse`, `idUtilisateur`),
  INDEX `idAdresse_idx` (`idAdresse` ASC) VISIBLE,
  INDEX `idClinique_idx` (`idClinique` ASC) VISIBLE,
  INDEX `idPlageHoraire_idx` (`idPlageHoraire` ASC) VISIBLE,
  INDEX `idService Medecin_idx` (`idServices` ASC) VISIBLE,
  UNIQUE INDEX `nomMedecin_UNIQUE` (`nomMedecin` ASC) VISIBLE,
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `idAdresse`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idClinique`
    FOREIGN KEY (`idClinique`)
    REFERENCES `mydb`.`clinique` (`idClinique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPlageHoraire`
    FOREIGN KEY (`idPlageHoraire`)
    REFERENCES `mydb`.`disponibiliteMed` (`idPlageHoraire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServices`
    FOREIGN KEY (`idServices`)
    REFERENCES `mydb`.`Services Medecin` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rendezvous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rendezvous` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rendezvous` (
  `idRendezvous` INT NOT NULL AUTO_INCREMENT,
  `dateRdv` DATETIME(6) NOT NULL,
  `raisonRdv` VARCHAR(45) NOT NULL,
  `detailsRdv` VARCHAR(45) NOT NULL,
  `idPatient` INT NOT NULL,
  `idMedecin` INT NOT NULL,
  `idClinique` INT NOT NULL,
  PRIMARY KEY (`idRendezvous`, `idPatient`, `idMedecin`, `idClinique`),
  INDEX `fk_rendezvous_patient1_idx` (`idPatient` ASC) VISIBLE,
  INDEX `fk_rendezvous_medecin1_idx` (`idMedecin` ASC, `idClinique` ASC) VISIBLE,
  INDEX `idClinique_idx` (`idClinique` ASC) VISIBLE,
  CONSTRAINT `fk_rendezvous_patient1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `mydb`.`patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rendezvous_medecin1`
    FOREIGN KEY (`idMedecin` , `idClinique`)
    REFERENCES `mydb`.`medecin` (`idMedecin` , `idClinique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMedecin`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `mydb`.`medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPatient`
    FOREIGN KEY (`idPatient`)
    REFERENCES `mydb`.`patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idClinique`
    FOREIGN KEY (`idClinique`)
    REFERENCES `mydb`.`clinique` (`idClinique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fichiers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fichiers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fichiers` (
  `idfichiers` INT NOT NULL,
  `dateFichier` DATE NOT NULL,
  `typeFichier` VARCHAR(45) NULL,
  `idPatient` INT NOT NULL,
  `idMedecin` INT NOT NULL,
  PRIMARY KEY (`idfichiers`, `idPatient`, `idMedecin`),
  INDEX `idMedecin_idx` (`idMedecin` ASC) VISIBLE,
  INDEX `idPatient_idx` (`idPatient` ASC) VISIBLE,
  CONSTRAINT `idPatient`
    FOREIGN KEY (`idPatient`)
    REFERENCES `mydb`.`patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMedecin`
    FOREIGN KEY (`idMedecin`)
    REFERENCES `mydb`.`medecin` (`idMedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `nomAdmin` VARCHAR(45) NULL,
  `prenomAdmin` VARCHAR(45) NULL,
  `idUtilisateur` INT NULL,
  PRIMARY KEY (`idadmin`),
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`adresse`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (1, '3350 ', 'Sherbrooke', 'Montreal', 'QC', 'H3Y2N1');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (2, '12', 'Chambly', 'Anjou', 'QC', 'H1K3T5');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (3, '11800', 'Gouin', 'Riviere des Prairies', 'QC', 'H1L3A9');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (4, '2154', 'Sheffield', 'Kirkland', 'QC', 'H3H2K2');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (5, '8820', 'LeCorbusier', 'Laval', 'QC', 'J9K2M5');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (6, '354', 'Marois', 'Longeuil', 'QC', 'J2X1J0');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (7, '2254', 'Pie-Ix', 'Montreal', 'QC', 'H1X2W2');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (8, '5680', 'Langelier', 'Saint-Leonard', 'QC', 'H2Y1B3');
INSERT INTO `mydb`.`adresse` (`idAdresse`, `numRue`, `nomRue`, `nomVille`, `nomProvince`, `codePostal`) VALUES (9, '6520', 'Jean-Brillant', 'Cote-des-Neiges', 'QC', 'H3A2L2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`utilisateur`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (idUtilisateur, 'username', 'password', 'firstLogin');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (1, 'lapain2002', 'Pantin20', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (2, 'Banane*80', 'MielJaune88', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (3, 'moimeme00', 'docx_medx99', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (4, 'leDoc11', 'Resident_345', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (5, 'Halley_Kennedy21', 'Patty21!', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (6, 'harry_potter', 'dumbledore01', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (7, 'soucoupe101', 'Roswell1950', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (8, 'lunar_sun', 'umbrella_door', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (9, 'docteurJean', 'Renaud1960', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (10, 'AudreyHep', 'Cinema_2021', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (11, 'tigerWoods', 'mcLeod3', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (12, 'Vagr_34', 'rainbow285', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (13, 'Quinn_Flynn', 'MouseCar824', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (14, 'Gloria_Moon', 'Moonshine$34', 'N');
INSERT INTO `mydb`.`utilisateur` (`idUtilisateur`, `firstLogin`, `password`, `usename`) VALUES (15, 'brad_green00', 'braddy105!', 'N');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`patient`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (1, 'Nixon', 'Tiger', 'TGRS20108930', '12', '', 'M', 'tigrNx19@hotmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (2, 'Winters', 'Garrett', 'GATR2020394', '11', '', 'M', 'garret1963@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (3, 'Cox', 'Ashton', 'ASCO2030291', '14', '', 'M', 'ashcox2002@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (4, 'Kelly', 'Cedric', 'CEKE20209949', '20', '', 'M', 'sedKelly24@yahoo.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (5, 'Satou', 'Airi', 'AISA20209301', '22', '', 'F', 'airi1978@sympatico.ca', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (6, 'Williamson', 'Brielle', 'BRWI20302923', '18', '', 'F', 'brielle2004@hotmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (7, 'Herrod', 'Chandler', 'HECH20393920', '11', '', 'M', 'chandlerHer@aol.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (8, 'Davis', 'Rhona', 'RHDA20293920', '14', '', 'F', 'rhonaDavis@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (9, 'Hurst', 'Colleen', 'HUCO284392082', '16', '', 'F', 'colleen14@bell.net', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (10, 'Frost', 'Sonya', 'FROS293828392', '22', '', 'F', 'oiseau25@hotmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (11, 'Gaines', 'Jena', 'JEGA282921848', '13', '', 'F', 'jenaGaines18@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (12, 'Flynn', 'Quinn', 'FLYQ283984928', '19', '', 'M', 'qbert@live.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (13, 'Charde', 'Marshall', 'MARC282843920', '20', '', 'M', 'marsh_88@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (14, 'Kennedy', 'Haley', 'KENH2828932843', '26', '', 'F', 'halleycomet@aol.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (15, 'Silva', 'Michael', 'SILM2029399288', '14', '', 'M', 'MikeSilva@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (16, 'Fitzpatrick', 'Tatyana', 'FITT2093988488', '18', '', 'F', 'fitztat20@verizon.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (17, 'Byrd', 'Paul', 'BYRP292388482', '14', '', 'M', 'birdwatcher@hotmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (18, 'Little', 'Gloria', 'LITG209283884', '18', '', 'F', 'gloria223344@gmail.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (19, 'Greer', 'Bradley', 'GREB229388293', '22', '', 'M', 'bradgree10@videotron.com', , );
INSERT INTO `mydb`.`patient` (`idPatient`, `nomPatient`, `prenomPatient`, `ramqPatient`, `numSequence`, `dateNaissance`, `sexePatient`, `courrielPatient`, `idAdresse`, `idUtilisateur`) VALUES (20, 'Rios', 'Daisy', 'RIOD292838898', '10', '', 'F', 'daydreamer@msn.com', , );

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Services`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Services` (`idServices`, `typeServices`, `idClinique`) VALUES (1, 'Prise de sang', Berri);
INSERT INTO `mydb`.`Services` (`idServices`, `typeServices`, `idClinique`) VALUES (2, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`clinique`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`clinique` (`idClinique`, `nomClinique`, `courrielClinique`, `telClinique`, `idAdresse`, `idMedecin`, `idServices`, `idUtilisateur`) VALUES (1, 'Clinique Beausejour', 'beausejourClinique@videotron.com', '514-576-3420', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`clinique` (`idClinique`, `nomClinique`, `courrielClinique`, `telClinique`, `idAdresse`, `idMedecin`, `idServices`, `idUtilisateur`) VALUES (2, 'Notre-Dame-de-Grace', 'cliniqueNDG@live.com', '514-775-2010', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`clinique` (`idClinique`, `nomClinique`, `courrielClinique`, `telClinique`, `idAdresse`, `idMedecin`, `idServices`, `idUtilisateur`) VALUES (3, 'Clinique du Nord-Est', 'medic@CNE.net', '450-215-2500', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`clinique` (`idClinique`, `nomClinique`, `courrielClinique`, `telClinique`, `idAdresse`, `idMedecin`, `idServices`, `idUtilisateur`) VALUES (4, 'Clinique Villeray', 'villeray@cliniqueRV.com', '514-455-2380', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`clinique` (`idClinique`, `nomClinique`, `courrielClinique`, `telClinique`, `idAdresse`, `idMedecin`, `idServices`, `idUtilisateur`) VALUES (5, 'Clinique Bonsecours', 'bonsecours@medic.ca', '514-650-4425', DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

